### ISSUE TITLE
Adding an improved CI

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/veneer#6]
Hello Tom!
I am planning to contribute to your project(s).
How come that there are zero unit tests? I'm also missing hundreds of GitHub stars.

> Changing the world one line of code at a time.

**Comment by betterthanclay** [comment]
Hi Viktor.

Unit tests are planned, but right now I'm still shaping how all of the different DecodeLabs packages will interact with each other on a larger scale to form a broader framework - things are still moving around a fair bit and there are quite a few more in the pipeline, and it hasn't made that much sense to commit to writing lots of unit tests that would be obsolete before final public release, especially when PHPStan takes care of a lot of the testing scenarios anyway. 

These are ultimately pre-release packages and shouldn't be used in production yet unless you're willing to deal with things changing a lot!

Focus will be on moving towards proper v1 releases for most of the current packages, including unit tests, proper documentation, website, etc, however due to other commitments in and out of work, my time has been very limited - it's still going to take a while to get there!
