### ISSUE TITLE
Detailed description

### ISSUE THREAD

**Issue by szepeviktor** [decodelabs/veneer#9]
Do you have a blog post that explains what (and **how**) veneer does?
Actually I have no clue :)

**Comment by szepeviktor** [comment]
something like "lazy loading"?

**Comment by betterthanclay** [comment]
There's no blog post, only what's in the README.

Essentially, it allows you to bind an instance of a class to a static wrapper that allows you to call it statically through a nominated class name. It allows for much neater and easier code while maintaining testability and decoupling.

<code>DecodeLabs\Tagged</code> for example, doesn't actually exist in the Tagged package. Veneer binds a lazy loaded instance of <code>DecodeLabs\Tagged\Factory</code> to it at runtime, so you can call it like this:

```
use DecodeLabs\Tagged as Html;
echo Html::p('Hello world');
```
rather than
```
$html = new DecodeLabs\Tagged\Factory();
echo $factory->p('Hello world');
```

It does this using <code>class_alias()</code>, an autoloader and a registry of types that need to be bound at runtime.
It also provides a plugin mechanism so you can add static members to the interface - for example, the Time plugin in Tagged:

```
echo Html::$time->date('now');
```

**Comment by szepeviktor** [comment]
Thank you for the explanation.

I wish this would be included in README!

**Comment by betterthanclay** [comment]
It's on my Todo list to improve the README for this project, it needs explaining in a more detailed way for sure.
